---
- name: Load apt key for docker engine
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  become: yes

- name: Add docker repository
  apt_repository: repo='deb https://download.docker.com/linux/ubuntu xenial stable' state=present filename='docker'
  become: yes

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=86400
  become: yes

- name: Install docker-engine package
  apt: name=docker-ce
  register: aptinstall
  become: yes

- name: Install python-pip package
  apt: name=python-pip
  become: yes

- name: Install docker-py module
  pip: name=docker-py
  become: yes
  
- name: Create docker group
  group: name=docker state=present
  become: yes

- name: Add docker group to ansible
  user: name={{ ansible_user }} group=docker
  become: yes

#- name: Copy docker logging config
#  template:
#    src: templates/daemon.json.j2
#    dest: /etc/docker/daemon.json
#  become: yes

- name: Start docker engine
  service: name=docker state=started
  become: yes
  
- name: Restart machine
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  become: true
  ignore_errors: true
  when: aptinstall.changed

- name: Waiting(60 sec) for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=40 timeout=120
  become: false
  when: aptinstall.changed