version: '3.4'
services:

  #indypool should be created beforehand, with schemas and credentials issued for user auth
  #  indypool:
  #    network_mode: host
  #    image: "teamblockchain/indy-pool:1.7.0"
  #    ports:
  #      - "9701-9708:9701-9708"
  #    container_name: indypool

  cordabaseimage:
    network_mode: host
    build:
      context: ./devops/profile/develop
      dockerfile: Dockerfile-corda
      target: libindyjava
    image: libindyjava

# -------------------- Corda nodes -----------------------
  notary:
    network_mode: host
    build:
      context: ./build/nodes/Notary
      dockerfile: Dockerfile-corda
    ports:
      - "10001:10001"
      - "10002:10002"
      - "10003:10003"
    container_name: notary
    deploy:
      resources:
        limits:
          memory: 500m

# -------------------- Spring nodes -----------------------
  hospitalweb:
    network_mode: host
    build:
      context: ./webapp
      dockerfile: Dockerfile-web
    ports:
      - "8081:8081"
    environment:
      - "SPRING_PROFILES_ACTIVE=swagger"
      - "indy_trustedCredentialsIssuerDID=XXdcqNCR9EkhpGwosNkF58"
    container_name: hospitalweb
    deploy:
      resources:
        limits:
          memory: 50m

  # -------------------- Indy agents -----------------------
  agent94:
    image: teamblockchain/indy-agent-python:eee0475e1ac3417990a4ec55164b1a32eb3bd6d5
    ports:
      - "8094:8094"
    environment:
      - "PORT=8094"
    hostname: agent
    volumes:
      - ./hosts:/etc/hosts:ro
    container_name: agent94

  agent95:
    image: teamblockchain/indy-agent-python:eee0475e1ac3417990a4ec55164b1a32eb3bd6d5
    ports:
      - "8095:8095"
    environment:
      - "PORT=8095"
    hostname: agent
    volumes:
      - ./hosts:/etc/hosts:ro
    container_name: agent95

  agentInitiator:
    network_mode: host
    image: alpine:3.6
    container_name: agentInitiator
    depends_on:
      - agent94
      - agent95
    command: sh -c 'sleep 10; /usr/bin/wget --spider http://localhost:8094/; /usr/bin/wget --spider http://localhost:8095/'
