FROM ubuntu:18.04 AS libindyjava

RUN apt-get update && apt-get install -y openjdk-8-jre-headless software-properties-common

# Install libindy
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88 && \
    add-apt-repository "deb https://repo.sovrin.org/sdk/deb xenial stable"
# -o Acquire::https::*::Verify-Peer=false is to make build work in environments with filtered https
RUN apt-get -o Acquire::https::repo.sovrin.org::Verify-Peer=false update && \
    apt-get -o Acquire::https::repo.sovrin.org::Verify-Peer=false install -y libindy=1.8.2

FROM libindyjava

ENV CORDA_VERSION=${BUILDTIME_CORDA_VERSION}

# Set image labels
LABEL net.corda.version = ${CORDA_VERSION}

# Add user
RUN addgroup corda && \
    useradd -g corda corda && \
    # Create /opt/corda directory && \
    mkdir -p /opt/corda/plugins && \
    mkdir -p /opt/corda/logs

# Copy corda files
ADD corda.jar               /opt/corda/corda.jar
ADD node.conf               /opt/corda/node.conf
ADD network-parameters      /opt/corda/
ADD cordapps/               /opt/corda/cordapps
ADD additional-node-infos/  /opt/corda/additional-node-infos
ADD certificates/           /opt/corda/certificates
ADD persistence*            /opt/corda/
ADD indyconfig/             /opt/corda/indyconfig
ADD genesis/                /opt/corda/genesis

# Working directory for Corda
WORKDIR /opt/corda
ENV HOME=/opt/corda
RUN chown -R corda:corda /opt/corda
USER corda

# ENV RUST_LOG=trace

# Start it
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", \
     "-Dcapsule.jvm.args='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n'", \
     "corda.jar"]